version: "3.6"
services:

  # Postgres Database
  database:
    image: postgres:12.3-alpine
    env_file:
      - .env.prod
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  # Core Admin (Backend Django)
  backend:
    build: ./backend
    volumes:
      # Directory of static file of Django
      - ./archive/static:/app/static
      - ./log:/log
    env_file:
      - .env.prod
    depends_on:
      - database

  # Web Server Nginx with React Frontend
  frontend:
    build: ./frontend
    ports:
      - 80:8080
    volumes:
      # Directory of static file of Django
      - ./archive/static:/var/www/django_static
      # Nginx configuration file
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - backend
