version: "3.6"
services:

  # Database
  database:
    image: postgres:12.3-alpine
    env_file:
      - .env.prod
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  # Core Admin (Backend Django)
  backend:
    build: ./backend
    env_file:
      - .env.prod

  frontend:
    build: ./frontend
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
